### ISSUE TITLE
Kanban board for the Capstone project

### ISSUE THREAD

**Issue by Hombre2014** [Hombre2014/Book-a-class#21]
Here is the link to our Kanban [board](https://github.com/Hombre2014/Book-a-class/projects/1).

We are a team of three people:

[Yuriy Chamkoriyski](https://github.com/Hombre2014)
[Mubarak A Ibrahim](https://github.com/imubarak234)
[Kalolo Chola Lemba](https://github.com/KayLemba)

Screenshot of the Kanban board setup:

![Kanban_initial](https://user-images.githubusercontent.com/8495547/167175994-99a370d6-7116-4a2e-b968-a9b18bac075a.png)

**Comment by MuriloRoque** [comment]
Hi @Hombre2014, @imubarak234, @KayLemba,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by Hombre2014** [comment]
Thank you very much for your quick review.
